version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      engine-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/apps/cockpit"
    schedule:
      interval: "weekly"
    groups:
      cockpit-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
