/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#081425",
        surface: "#081425",
        "surface-main": "#0B0E14",
        "surface-sidebar": "#0F1117",
        "surface-container-lowest": "#040e1f",
        "surface-container-low": "#111c2d",
        "surface-container": "#152031",
        "surface-container-high": "#1f2a3c",
        "surface-container-highest": "#2a3548",
        "surface-variant": "#2a3548",
        "on-background": "#d8e3fb",
        "on-surface": "#d8e3fb",
        "on-surface-variant": "#c3c5d8",
        primary: "#b7c4ff",
        "primary-container": "#2e62ff",
        "on-primary": "#002682",
        "on-primary-container": "#f7f6ff",
        secondary: "#b7c8e1",
        "secondary-container": "#3a4a5f",
        "border-subtle": "#1E293B",
        outline: "#8d90a2",
        "outline-variant": "#434656",
        "status-blocked": "#EF4444",
        "status-waiting": "#F59E0B",
        "status-done": "#10B981",
        "track-demo": "#008FD3",
        "track-ai": "#8B5CF6",
        "track-biz": "#EC4899",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Geist", "Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        metadata: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
        "code-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
      },
      maxWidth: {
        cockpit: "1440px",
      },
      spacing: {
        gutter: "24px",
        "sidebar-width": "280px",
      },
    },
  },
  plugins: [],
};
