/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--color-background) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        "surface-main": "rgb(var(--color-surface-main) / <alpha-value>)",
        "surface-sidebar": "rgb(var(--color-surface-sidebar) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "surface-container-low": "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "surface-container": "rgb(var(--color-surface-container) / <alpha-value>)",
        "surface-container-high": "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "surface-variant": "rgb(var(--color-surface-variant) / <alpha-value>)",
        "on-background": "rgb(var(--color-on-background) / <alpha-value>)",
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--color-primary-container) / <alpha-value>)",
        "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
        "on-primary-container": "rgb(var(--color-on-primary-container) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary) / <alpha-value>)",
        "secondary-container": "rgb(var(--color-secondary-container) / <alpha-value>)",
        "border-subtle": "rgb(var(--color-border-subtle) / <alpha-value>)",
        outline: "rgb(var(--color-outline) / <alpha-value>)",
        "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
        "status-blocked": "rgb(var(--color-status-blocked) / <alpha-value>)",
        "status-waiting": "rgb(var(--color-status-waiting) / <alpha-value>)",
        "status-done": "rgb(var(--color-status-done) / <alpha-value>)",
        "track-demo": "rgb(var(--color-track-demo) / <alpha-value>)",
        "track-ai": "rgb(var(--color-track-ai) / <alpha-value>)",
        "track-biz": "rgb(var(--color-track-biz) / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      fontFamily: {
        sans: ["var(--theme-body-font)"],
        display: ["var(--theme-display-font)"],
        mono: ["var(--theme-mono-font)"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        metadata: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
        "code-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
      },
      maxWidth: {
        cockpit: "1440px",
      },
      spacing: {
        gutter: "24px",
        "sidebar-width": "280px",
      },
    },
  },
  plugins: [],
};
