#!/usr/bin/env node
// Configure this repo's KB MCP server and skills for Claude Code on this machine.
//
//   node scripts/configure-claude.mjs            # configure with writes enabled
//   node scripts/configure-claude.mjs --no-writes  # read-only KB (dryRun still works)
//   node scripts/configure-claude.mjs --skip-smoke # skip the handshake verification
//
// What it does (all idempotent):
//   1. Ensures dependencies are installed (so `tsx` is available).
//   2. Writes .mcp.json pointing at this machine's absolute node + tsx paths.
//      Claude Code spawns MCP servers with a minimal PATH, so bare `npx`/`node`
//      cannot be resolved — absolute paths are the reliable fix.
//   3. Approves the server in .claude/settings.local.json so it loads without a prompt.
//   4. Syncs skills/* into .claude/skills/* so Claude Code discovers them.
//   5. Adds the generated, machine-specific files to .gitignore.
//   6. Runs the MCP smoke test to confirm the handshake works.

import { execFileSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SERVER_NAME = "kb";
const SERVER_ENTRY_REL = "tools/kb-mcp-server/server.ts";
const SMOKE_TEST_REL = "tools/kb-mcp-server/smoke-test.ts";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = new Set(process.argv.slice(2));
const enableWrites = !args.has("--no-writes");
const skipSmoke = args.has("--skip-smoke");

const isWindows = process.platform === "win32";
const nodeBin = process.execPath; // absolute path to the node running this script
const tsxBin = join(repoRoot, "node_modules", ".bin", isWindows ? "tsx.cmd" : "tsx");
const serverEntry = join(repoRoot, SERVER_ENTRY_REL);

function step(msg) {
  console.log(`\n▸ ${msg}`);
}

function readJson(path) {
  if (!existsSync(path)) return {};
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return {};
  }
}

function writeJson(path, value) {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

function copyDir(src, dest) {
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    if (entry === ".DS_Store") continue;
    const s = join(src, entry);
    const d = join(dest, entry);
    if (statSync(s).isDirectory()) copyDir(s, d);
    else copyFileSync(s, d);
  }
}

function ensureGitignore(root, entries) {
  const path = join(root, ".gitignore");
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  const lines = new Set(current.split(/\r?\n/).map((l) => l.trim()));
  const missing = entries.filter((e) => !lines.has(e));
  if (missing.length === 0) return;
  const header = "\n# Claude Code local config (generated by scripts/configure-claude.mjs)\n";
  const block = `${header}${missing.join("\n")}\n`;
  writeFileSync(path, current.endsWith("\n") || current === "" ? current + block : `${current}\n${block}`);
}

// 1. Dependencies (need tsx to run the TypeScript server) ----------------------
if (!existsSync(tsxBin)) {
  step("Installing dependencies (npm install)…");
  execFileSync(isWindows ? "npm.cmd" : "npm", ["install"], { cwd: repoRoot, stdio: "inherit" });
}
if (!existsSync(tsxBin)) {
  console.error(`\n✗ tsx not found at ${tsxBin} even after npm install. Aborting.`);
  process.exit(1);
}
if (!existsSync(serverEntry)) {
  console.error(`\n✗ Server entry not found at ${serverEntry}. Aborting.`);
  process.exit(1);
}

// 2. .mcp.json with absolute paths --------------------------------------------
step("Writing .mcp.json…");
const mcpPath = join(repoRoot, ".mcp.json");
const mcp = readJson(mcpPath);
mcp.mcpServers = {
  ...(mcp.mcpServers ?? {}),
  [SERVER_NAME]: {
    command: nodeBin,
    args: [tsxBin, serverEntry],
    env: enableWrites ? { KB_MCP_ENABLE_WRITES: "true" } : {},
  },
};
writeJson(mcpPath, mcp);
console.log(`  command: ${nodeBin}`);
console.log(`  args:    ${tsxBin} ${serverEntry}`);
console.log(`  writes:  ${enableWrites ? "enabled" : "disabled (dryRun still available)"}`);

// 3. Approve the server so Claude loads it without prompting -------------------
step("Approving MCP server in .claude/settings.local.json…");
const claudeDir = join(repoRoot, ".claude");
mkdirSync(claudeDir, { recursive: true });
const localSettingsPath = join(claudeDir, "settings.local.json");
const localSettings = readJson(localSettingsPath);
const approved = new Set(localSettings.enabledMcpjsonServers ?? []);
approved.add(SERVER_NAME);
localSettings.enabledMcpjsonServers = [...approved];
writeJson(localSettingsPath, localSettings);

// 4. Sync skills/* into .claude/skills/* --------------------------------------
step("Syncing skills into .claude/skills/…");
const skillsSrc = join(repoRoot, "skills");
const skillsDest = join(claudeDir, "skills");
let skillCount = 0;
if (existsSync(skillsSrc) && statSync(skillsSrc).isDirectory()) {
  mkdirSync(skillsDest, { recursive: true });
  for (const entry of readdirSync(skillsSrc)) {
    const srcDir = join(skillsSrc, entry);
    if (!statSync(srcDir).isDirectory()) continue;
    if (!existsSync(join(srcDir, "SKILL.md"))) continue;
    const destDir = join(skillsDest, entry);
    rmSync(destDir, { recursive: true, force: true });
    copyDir(srcDir, destDir);
    skillCount += 1;
    console.log(`  ${entry}`);
  }
}
console.log(skillCount === 0 ? "  (no skills found to sync)" : `  ${skillCount} skill(s) synced`);

// 5. Ignore the generated, machine-specific files -----------------------------
step("Updating .gitignore…");
ensureGitignore(repoRoot, [".mcp.json", ".claude/settings.local.json", ".claude/skills/"]);

// 6. Verify the MCP handshake -------------------------------------------------
if (skipSmoke) {
  console.log("\n(skipping smoke test)");
} else {
  step("Verifying MCP handshake (smoke test)…");
  try {
    execFileSync(nodeBin, [tsxBin, join(repoRoot, SMOKE_TEST_REL)], {
      cwd: repoRoot,
      stdio: "inherit",
      env: { ...process.env, KB_MCP_ENABLE_WRITES: enableWrites ? "true" : "" },
    });
  } catch {
    console.error("\n✗ Smoke test failed — the server did not complete the handshake.");
    process.exit(1);
  }
}

console.log(`
✅ Claude Code is configured for this repo.

   Next: fully quit Claude Code (Cmd+Q / Ctrl+Q) and reopen it from this folder.
   The "${SERVER_NAME}" MCP server and ${skillCount} skill(s) will load automatically.
`);
