#!/usr/bin/env node
// Register this repo's one KB MCP server with Claude Code, Codex, and Gemini CLI.
//
//   node scripts/configure-mcp.mjs
//   node scripts/configure-mcp.mjs --client codex
//   node scripts/configure-mcp.mjs --profile full
//   node scripts/configure-mcp.mjs --no-writes
//   node scripts/configure-mcp.mjs --skip-smoke
//
// The clients use different project-local config files, but every adapter launches
// the same tools/kb-mcp-server/server.ts process with the same environment.

import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SERVER_NAME = "kb";
const SERVER_ENTRY_REL = "tools/kb-mcp-server/server.ts";
const SMOKE_TEST_REL = "tools/kb-mcp-server/smoke-test.ts";
const SUPPORTED_CLIENTS = new Set(["claude", "codex", "gemini", "all"]);
const MANAGED_TOML_START = "# >>> Grounded Knowledge Engine MCP (managed by setup:mcp)";
const MANAGED_TOML_END = "# <<< Grounded Knowledge Engine MCP";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const cliArgs = process.argv.slice(2);
const enableWrites = !cliArgs.includes("--no-writes");
const skipSmoke = cliArgs.includes("--skip-smoke");
const requestedClient = readOption(cliArgs, "--client") || "all";
const requestedProfile = readOption(cliArgs, "--profile") || "core";

if (!SUPPORTED_CLIENTS.has(requestedClient)) {
  console.error(`\n✗ Unsupported client "${requestedClient}". Use claude, codex, gemini, or all.`);
  process.exit(1);
}

const clients = requestedClient === "all"
  ? ["claude", "codex", "gemini"]
  : [requestedClient];
const isWindows = process.platform === "win32";
const nodeBin = process.execPath;
const tsxBin = join(repoRoot, "node_modules", ".bin", isWindows ? "tsx.cmd" : "tsx");
const serverEntry = join(repoRoot, SERVER_ENTRY_REL);
if (!new Set(["core", "full"]).has(requestedProfile)) {
  console.error(`\n✗ Unsupported profile "${requestedProfile}". Use core or full.`);
  process.exit(1);
}
const serverEnv = {
  KB_MCP_PROFILE: requestedProfile,
  ...(enableWrites ? { KB_MCP_ENABLE_WRITES: "true" } : {}),
};

function readOption(args, name) {
  const equalsArg = args.find((arg) => arg.startsWith(`${name}=`));
  if (equalsArg) return equalsArg.slice(name.length + 1).trim().toLowerCase();
  const index = args.indexOf(name);
  return index >= 0 ? String(args[index + 1] || "").trim().toLowerCase() : "";
}

function step(message) {
  console.log(`\n▸ ${message}`);
}

function readJson(path) {
  if (!existsSync(path)) return {};
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch (error) {
    console.error(`\n✗ Cannot safely update invalid JSON at ${path}: ${error.message}`);
    process.exit(1);
  }
}

function writeJson(path, value) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

function quoteToml(value) {
  return JSON.stringify(value);
}

function removeTomlTables(current, tableNames) {
  const kept = [];
  let skip = false;
  for (const line of current.split(/\r?\n/)) {
    const header = line.match(/^\s*\[([^\]]+)\]\s*(?:#.*)?$/);
    if (header) skip = tableNames.has(header[1]);
    if (!skip) kept.push(line);
  }
  return kept.join("\n").trimEnd();
}

function replaceManagedTomlBlock(current, block) {
  const start = current.indexOf(MANAGED_TOML_START);
  const end = current.indexOf(MANAGED_TOML_END);
  if (start >= 0 && end >= start) {
    const afterEnd = end + MANAGED_TOML_END.length;
    return `${current.slice(0, start)}${block}${current.slice(afterEnd)}`.trimEnd() + "\n";
  }

  // Upgrade an existing unmanaged kb entry without duplicating TOML tables.
  const prefix = removeTomlTables(current, new Set([
    `mcp_servers.${SERVER_NAME}`,
    `mcp_servers.${SERVER_NAME}.env`,
  ]));
  return `${prefix}${prefix ? "\n\n" : ""}${block}\n`;
}

function ensureGitignore(entries) {
  const path = join(repoRoot, ".gitignore");
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  const lines = new Set(current.split(/\r?\n/).map((line) => line.trim()));
  const missing = entries.filter((entry) => !lines.has(entry));
  if (missing.length === 0) return;
  const header = "\n# Agent-local MCP config (generated by scripts/configure-mcp.mjs)\n";
  const block = `${header}${missing.join("\n")}\n`;
  writeFileSync(path, current.endsWith("\n") || current === "" ? current + block : `${current}\n${block}`);
}

function configureClaude() {
  step("Configuring Claude Code (.mcp.json)…");
  const mcpPath = join(repoRoot, ".mcp.json");
  const mcp = readJson(mcpPath);
  mcp.mcpServers = {
    ...(mcp.mcpServers ?? {}),
    [SERVER_NAME]: {
      command: nodeBin,
      args: [tsxBin, serverEntry],
      env: serverEnv,
    },
  };
  writeJson(mcpPath, mcp);

  const settingsPath = join(repoRoot, ".claude", "settings.local.json");
  const settings = readJson(settingsPath);
  const approved = new Set(settings.enabledMcpjsonServers ?? []);
  approved.add(SERVER_NAME);
  settings.enabledMcpjsonServers = [...approved];
  writeJson(settingsPath, settings);
}

function configureCodex() {
  step("Configuring Codex (.codex/config.toml)…");
  const configPath = join(repoRoot, ".codex", "config.toml");
  const current = existsSync(configPath) ? readFileSync(configPath, "utf8") : "";
  const envLines = [
    `[mcp_servers.${SERVER_NAME}.env]`,
    `KB_MCP_PROFILE = ${quoteToml(requestedProfile)}`,
  ];
  if (enableWrites) envLines.push(`KB_MCP_ENABLE_WRITES = "true"`);
  const envBlock = `\n${envLines.join("\n")}\n`;
  const block = [
    MANAGED_TOML_START,
    `[mcp_servers.${SERVER_NAME}]`,
    `command = ${quoteToml(nodeBin)}`,
    `args = [${quoteToml(tsxBin)}, ${quoteToml(serverEntry)}]`,
    envBlock.trimEnd(),
    MANAGED_TOML_END,
  ].filter(Boolean).join("\n");
  mkdirSync(dirname(configPath), { recursive: true });
  writeFileSync(configPath, replaceManagedTomlBlock(current, block));
}

function configureGemini() {
  step("Configuring Gemini CLI (.gemini/settings.json)…");
  const settingsPath = join(repoRoot, ".gemini", "settings.json");
  const settings = readJson(settingsPath);
  settings.mcpServers = {
    ...(settings.mcpServers ?? {}),
    [SERVER_NAME]: {
      command: nodeBin,
      args: [tsxBin, serverEntry],
      cwd: repoRoot,
      env: serverEnv,
    },
  };
  writeJson(settingsPath, settings);
}

// 1. Dependencies -------------------------------------------------------------
if (!existsSync(tsxBin)) {
  step("Installing dependencies (npm install)…");
  execFileSync(isWindows ? "npm.cmd" : "npm", ["install"], {
    cwd: repoRoot,
    stdio: "inherit",
  });
}
if (!existsSync(tsxBin)) {
  console.error(`\n✗ tsx not found at ${tsxBin} even after npm install. Aborting.`);
  process.exit(1);
}
if (!existsSync(serverEntry)) {
  console.error(`\n✗ Server entry not found at ${serverEntry}. Aborting.`);
  process.exit(1);
}

// 2. Client adapters ----------------------------------------------------------
for (const client of clients) {
  if (client === "claude") configureClaude();
  if (client === "codex") configureCodex();
  if (client === "gemini") configureGemini();
}

// 3. Ignore generated machine-specific files ---------------------------------
step("Updating .gitignore…");
ensureGitignore([
  ".mcp.json",
  ".claude/settings.local.json",
  ".codex/config.toml",
  ".gemini/settings.json",
]);

// 4. Verify the one shared server ---------------------------------------------
if (skipSmoke) {
  console.log("\n(skipping smoke test)");
} else {
  step("Verifying the shared MCP server handshake…");
  try {
    execFileSync(nodeBin, [tsxBin, join(repoRoot, SMOKE_TEST_REL)], {
      cwd: repoRoot,
      stdio: "inherit",
      env: { ...process.env, KB_MCP_ENABLE_WRITES: enableWrites ? "true" : "" },
    });
  } catch {
    console.error("\n✗ Smoke test failed — the server did not complete the handshake.");
    process.exit(1);
  }
}

console.log(`
✅ The "${SERVER_NAME}" MCP server is configured for: ${clients.join(", ")}.

   All clients launch the same server:
   ${serverEntry}

   Writes: ${enableWrites ? "enabled" : "disabled (dryRun remains available)"}
   Profile: ${requestedProfile}
   Restart the configured client(s) from this repository to load the tools.
`);
